name: Gitea Actions
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

env:
  RECORDS: ${{ secrets.RECORDS }}
  API_TOKEN: ${{ secrets.API_TOKEN }}
  DOMAIN: ${{ secrets.DOMAIN }}
  ZONE_ID: ${{ secrets.ZONE_ID }}


jobs:
  build:
    runs-on: deepin
    
    steps:
      - name: Check out repository code
        working-directory: /home/deepin/actions/work_CF
        uses: actions/checkout@v3

      - name: PWD
        working-directory: /home/deepin/actions/work_CF
        run: |
          pwd

      - name: Install pip dependencies
        working-directory: /home/deepin/actions/work_CF
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Virtual Environment
        working-directory: /home/deepin/actions/work_CF
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Run Python script
        working-directory: /home/deepin/actions/work_CF
        run: python3 main.py

      - name: Clean up
        working-directory: /home/deepin/actions/work_CF
        run: rm -rf venv
