name: Gitea Actions
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  build:
    runs-on: deepin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Run Python script
        run: python main.py

      - name: Clean up
        run: rm -rf venv
